server:
  port: 8080

spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s

jwt:
  secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437