spring:
  application:
    name: document-service
  elasticsearch:
    uris: http://localhost:9200
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8083

document-process:
  url: http://localhost:8000/upload/

jwt:
  secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437