spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb+srv://faker05122004:05122004@cluster0.mtqupom.mongodb.net/pdfminer-users?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

jwt:
  secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000
  refresh-token:
    expiration: 604800000